### ISSUE TITLE
After apostrophe update on 3.0.0-aplha.3 gatsby GraphQL error 

### ISSUE THREAD

**Issue by nikolalakovic85** [apostrophecms/demo-a3-headless#2]
## To Reproduce

Step by step instructions to reproduce the behavior:

> 1. gatsby-demo-apostrophe (https://github.com/apostrophecms/gatsby-demo-apostrophe) not working after apostrophe update
> 2.  I've got error:  Cannot query field "_rendered" on type "AposStaffMemberPhoto"
> 3.  _rendered property is missing (screenshot attached)

<img width="1437" alt="Screenshot 2021-02-17 at 12 37 29 AM" src="https://user-images.githubusercontent.com/57252231/108135472-768a4a80-70b8-11eb-83ac-b497a472d1f3.png">

**Comment by abea** [comment]
I pinned this to the `3.0.0-alpha.3` version to avoid continued breaks, but the critical area rendering update was merged a few days after that branch was published. Unfortunately we haven't published a new 3.0 version since then. For now you can comment out the "photo" part of the query in `staff.js`:

```
export const query = graphql`
  query StaffQuery {
    allAposStaffMember {
      nodes {
        id
        jobTitle
        title
        funFact
        # photo {
        #   _rendered
        # }
      }
    }
  }
`
```

We'll have a new version of Apostrophe 3 published next week with the feature and I'll update the Gatsby demo at that time.

Apologies for the trouble. This is what we get for trying to release a demo during the alpha phase!

**Comment by nikolalakovic85** [comment]
Great news! I will wait for a new version! Thanks!

**Comment by abea** [comment]
@nikolalakovic85 Please give the new `main` branch a try here. All the good things are in Apostrophe `3.0.0-alpha.4` and I'm pinning to that since core will continue to change. I used yarn to test and the Gatsby demo also seems to run nicely with this update.

Thanks again for the report!

**Comment by nikolalakovic85** [comment]
Great @abea! I will test it now! Thanks!
